#!/usr/bin/env node
// AI context tool — generates AI_MAP.md, a compact, always-current index of the
// codebase for AI agents: every source module with its one-line purpose and its
// exported symbols. Lets an agent orient in seconds instead of reading ~33k
// lines. Deterministic output (sorted) so diffs stay small.
//
//   npm run ai:map          # regenerate AI_MAP.md
//   node scripts/ai-map.mjs --stdout   # print instead of writing
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ROOTS = ['src', 'server/src'];
const SKIP = /(^|\/)(__tests__|node_modules|dist)(\/|$)/;

/** all *.ts files under the given roots, excluding tests/build output */
function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    const rel = relative(ROOT, full);
    if (SKIP.test(rel)) continue;
    const st = statSync(full);
    if (st.isDirectory()) walk(full, out);
    else if (name.endsWith('.ts') && !name.endsWith('.d.ts') && !name.endsWith('.test.ts')) out.push(full);
  }
  return out;
}

/** first human sentence of the file's top comment, cleaned to one line */
function purpose(src) {
  const lines = src.split('\n');
  let text = '';
  if (lines[0]?.trimStart().startsWith('/*')) {
    for (const l of lines) {
      text += ' ' + l.replace(/^\s*\/?\*+\/?/, '').replace(/\*\/\s*$/, '');
      if (l.includes('*/')) break;
    }
  } else {
    for (const l of lines) {
      const t = l.trimStart();
      if (t.startsWith('//')) text += ' ' + t.slice(2);
      else break;
    }
  }
  text = text.replace(/\s+/g, ' ').trim();
  const stop = text.search(/(?<=[.:])\s/);
  if (stop > 0 && stop < 160) text = text.slice(0, stop + 1);
  return text.length > 180 ? text.slice(0, 177) + '…' : text;
}

/** exported symbols + re-exports, in source order */
function exportsOf(src) {
  const decls = [];
  const reexports = [];
  for (const raw of src.split('\n')) {
    const line = raw.trim();
    let m;
    if ((m = line.match(/^export\s+(?:default\s+)?(?:async\s+)?(function|const|let|class|interface|type|enum)\s+([A-Za-z0-9_]+)/))) {
      decls.push(`${m[2]}${m[1] === 'function' ? '()' : ''}`);
    } else if ((m = line.match(/^export\s*\*\s*from\s*['"]([^'"]+)['"]/))) {
      reexports.push(m[1]);
    } else if ((m = line.match(/^export\s*(?:type\s*)?\{\s*([^}]*)\bfrom\s*['"]([^'"]+)['"]/))) {
      reexports.push(m[2]);
    }
  }
  return { decls, reexports };
}

const files = ROOTS.flatMap((r) => walk(join(ROOT, r))).sort();
const byDir = new Map();
for (const f of files) {
  const rel = relative(ROOT, f);
  const dir = dirname(rel);
  if (!byDir.has(dir)) byDir.set(dir, []);
  byDir.get(dir).push({ rel, name: rel.split('/').pop() });
}

let out = '';
out += '# AI_MAP — codebase index for agents\n\n';
out += '> Auto-generated by `npm run ai:map` (scripts/ai-map.mjs). Do not edit by hand.\n';
out += '> Read this first to locate code, then open the file(s) you need. Rules and\n';
out += '> architecture live in `AGENTS.md`, `CLAUDE.md`, `ARCHITECTURE.md` and per-folder READMEs.\n\n';
out += `**Scope:** ${files.length} TypeScript modules across \`${ROOTS.join('`, `')}\`.\n\n`;

for (const dir of [...byDir.keys()].sort()) {
  out += `## \`${dir}/\`\n\n`;
  for (const { rel, name } of byDir.get(dir)) {
    const src = readFileSync(join(ROOT, rel), 'utf8');
    const p = purpose(src);
    const { decls, reexports } = exportsOf(src);
    out += `- **${name}**${p ? ` — ${p}` : ''}\n`;
    if (reexports.length) out += `  - re-exports: ${reexports.map((r) => `\`${r}\``).join(', ')}\n`;
    if (decls.length) {
      const shown = decls.slice(0, 24).map((d) => `\`${d}\``).join(', ');
      out += `  - exports: ${shown}${decls.length > 24 ? ` … (+${decls.length - 24})` : ''}\n`;
    }
  }
  out += '\n';
}

if (process.argv.includes('--stdout')) {
  process.stdout.write(out);
} else {
  writeFileSync(join(ROOT, 'AI_MAP.md'), out);
  const symbols = files.reduce((n, f) => n + exportsOf(readFileSync(f, 'utf8')).decls.length, 0);
  console.log(`AI_MAP.md written — ${files.length} modules, ${symbols} exported symbols.`);
}
